<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Monthly Appointments Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #E8A0BF; /* clinic-rose */
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #E8A0BF;
            font-size: 24px;
            margin: 0;
            font-family: 'Times New Roman', serif;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #777;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th, table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        table th {
            background-color: #f9f9f9;
            color: #555;
            text-transform: uppercase;
            font-size: 10px;
        }
        .summary-box {
            float: right;
            border: 1px solid #ddd;
            background-color: #fcfcfc;
            padding: 10px 20px;
            font-size: 14px;
        }
        .total-amount {
            color: #E8A0BF;
            font-weight: bold;
            font-size: 16px;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 10px;
            color: #aaa;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>AuraCare Clinic</h1>
        <p>Monthly Completed Appointments Report</p>
        <p><strong>Month:</strong> {{ $currentMonth }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Patient Name</th>
                <th>Service Availed</th>
                <th>Staff Notes Logged?</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            @forelse($appointments as $appt)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($appt->appointment_date)->format('M d, Y') }}</td>
                    <td>{{ $appt->user->name }}</td>
                    <td>{{ $appt->service->service_name }}</td>
                    <td>{{ $appt->treatmentRecord ? 'Yes' : 'No' }}</td>
                    <td>PHP {{ number_format($appt->service->price, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align: center; color: #999;">No completed appointments found for this month.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary-box">
        <strong>Total Completed Visits:</strong> {{ $appointments->count() }}<br><br>
        <strong>Total Revenue:</strong> <span class="total-amount">PHP {{ number_format($totalRevenue, 2) }}</span>
    </div>

    <div style="clear: both;"></div>

    <div class="footer">
        Generated by AuraCare Management System on {{ \Carbon\Carbon::now()->format('F d, Y h:i A') }}
    </div>

</body>
</html>